### ISSUE TITLE
[EPIC] Wrapper für die Jitsi API entwickeln

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#64]
> **As a** developer
> **I want** a simple api for jitsi
> **so that** I have mor reusable and well-structured code.

## Description:
Develop a deno module which wraps all needed jitsi interaction and provides clean and simple methods for the jimmi backend. Use old code whenever possible, do refactoring as needed and take care of good exception handling (not yet there). Use the old code to find all methods and api calls needed for jimmi.

### 🟢 In scope:
- [ ] Create a new repository named `jitsi-api-client`
- [ ] Implement a function to connect to the jitsi api
- [ ] Implement functions so that different commands can be executed on the jitsi api
- [ ] Implement functions to pass events from the jitsi api to the jimmi backend
- [ ] Develop a single method that takes a room and an optional password and then builds a full connection to this room

### 🔴 Not in scope:
- Every not related to the jitsi api
- Jimmi backend stuff
- Jimmi frontend stuff

## What should be the result?
A new module in an extra repository which handles all needed interactions with the jitsi api.

**Comment by p-fruck** [comment]
After creating the repo, we should move the related issues to `jitsi-api-client`
