### ISSUE TITLE
[EPIC] Develop a YouTube Module using Invidious

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#69]
> **As a** developer
> **I want** to have a module to get the audio stream from youtube
> **so that** I have more reusable and well-structured code.

## Description:
Develop a new deno module which handles all interaction with youtube. Use old code whenever possible, do refactoring as needed and take care of good exception handling (not yet there). Use the old code to find all methods and api calls needed for jimmi.

### 🟢 In scope:
- [ ] Create a new TypeScript module inside the `backend/lib` folder
- [ ] Implement a contructor that takes an invidious instance url as optional parameter. Use `snopyta` as default.
- [ ] Implement a function that takes a youtube link, extracts the youtube id and finds the correct audio file (ogg vorbis is preferred)
- [ ] **Optional**: Implement a function for searching a video by text input (search query)

### 🔴 Not in scope:
- Jimmi backend coding
- Everything not related to youtube or invidious

## What should be the result?
A new module which can be seamlessly included in the jimmi backend that has the required functions.
